version: "3.9"

services:
  db:
    image: docker.arvancloud.ir/postgres:latest
    volumes:
      - lib_pg_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_management
      - POSTGRES_USER=library_admin
      - POSTGRES_PASSWORD=admin
    restart: always

  backend:
    build: .
    command: >
      sh -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8001
      "
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"
    environment:
      - SECRET_KEY=abcdefghijk
      - DEBUG=True
      
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=library_admin
      - PG_PASSWORD=admin
      - PG_DB_NAME=library_management
    depends_on:
      - db
    restart: always

volumes:
  lib_pg_db: