version: "3.9"

services:
  db:
    image: docker.arvancloud.ir/postgres:latest
    volumes:
      - ./postgre/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    restart: always
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready -U postgres']
    #   interval: 10s
    #   timeout: 5s
    #   retries: 2

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./core:/usr/src/app
    ports:
      - "8001:8001"
    environment:
      - SECRET_KEY=test
      - DEBUG=True

    restart: always

    depends_on:
      - db